### ISSUE TITLE
Missing y coordinate in lineto directive throws an exception

### ISSUE THREAD

**Issue by Mogztter** [mogest/prawn-svg#90] opened 2017-02-01 22:50 UTC
The following SVG document is throwing an exception: https://drive.google.com/open?id=0B1rPjnFlfglqaEQzeFd2am84ME0

I believe the exception `nil can't be coerced into Float (TypeError)` is caused by a missing y coordinate in lineto directive.

Do you think that prawn SVG should be able to be read this document ?

A simple fix could be to check that `@last_point.last` is not `nil`: https://github.com/mogest/prawn-svg/blob/9299bd892a775bea38d6715c22eccdb89aa1c090/lib/prawn/svg/elements/path.rb#L71-L73

Here's the full stack trace:
```
/home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:73:in `+': nil can't be coerced into Float (TypeError)
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:73:in `parse_path_command'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:30:in `block in parse'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:25:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/path.rb:25:in `parse'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:48:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:129:in `block in process_child_elements'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `block in each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /home/guillaume/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rexml/element.rb:903:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:124:in `process_child_elements'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:53:in `parse_and_apply'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/elements/base.rb:43:in `process'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:48:in `block (2 levels) in draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/renderer.rb:236:in `save_graphics_state'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/internals.rb:31:in `save_graphics_state'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:43:in `block in draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/bounding_box.rb:198:in `init_bounding_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document/bounding_box.rb:159:in `bounding_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-svg-0.25.1/lib/prawn/svg/interface.rb:42:in `draw'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_renderer.rb:32:in `block in render_behind'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/document.rb:346:in `float'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_renderer.rb:32:in `render_behind'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:558:in `block in draw_fragment_underlays'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:557:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:557:in `draw_fragment_underlays'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:277:in `draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:148:in `block in format_and_draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `block in apply_font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:282:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:245:in `apply_font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:167:in `block in apply_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:160:in `apply_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/arranger.rb:136:in `apply_color_and_font_settings'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:147:in `format_and_draw_fragment'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:95:in `block in print_line'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:93:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:93:in `print_line'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/wrap.rb:61:in `wrap'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:15:in `wrap'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:223:in `block (4 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:101:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:282:in `font_size'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:216:in `block (3 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:182:in `text_rendering_mode'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:211:in `block (2 levels) in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:210:in `block in render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:209:in `render'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:376:in `fill_formatted_text_box'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:215:in `formatted_text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/prawn-2.1.0/lib/prawn/text.rb:167:in `text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:2483:in `typeset_text'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:1845:in `layout_prose'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:440:in `convert_paragraph'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:358:in `convert_section'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `block in content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `map'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104:in `content'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:177:in `convert_document'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor-pdf:23:in `<main>'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/guillaume/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

NOTE: I'm using Asciidoctor PDF 1.5.0 Alpha 13

Ref: https://github.com/asciidoctor/asciidoctor-pdf/issues/738

**Comment by mogest** [comment] 2017-02-01 23:55
Hi @Mogztter, thanks for the report.

I ran your attached file on prawn-svg 0.26.0.  It didn't crash and correctly rendered the PDF.  That's a bit strange, are you sure you sent the right file?  Maybe use a gist to get it to me, or pop it in a ZIP?

I'm happy to modify the code, but as per the spec, I'll make it terminate parsing if two coordinates are not specified for the `lineto`.

**Comment by mojavelinux** [comment] 2017-02-02 00:26
I tested, but now I think I may have used 0.25.1. I'll go back and test
with the latest release. If so, that's great news. No change is the best
change.

Le 1 févr. 2017 4:55 PM, "Roger Nesbitt" <notifications@github.com> a
écrit :

**Comment by mogest** [comment] 2017-02-02 00:51
I've made a code change because I feel like it should handle an incorrect number of arguments better than it does.

It's hard to know for certain what was happening with the SVG seeing as it doesn't crash on my system, but I suspect that commit will fix it anyway.

Would be grateful if you could test from the master branch and report back.

**Comment by mojavelinux** [comment] 2017-02-02 01:50
I can confirm that this happens with 0.25.2, but not 0.26.0. So an upgrade fixes the problem.

It actually appears to be a problem with a move command. The value is expected to be a 2D array, but at one point there is only one value in the array. This results in a nil value in the `@subpath_initial_point`, which later ends up being a nil value for `@last_point.y`. I think it's this path:

```ruby
<path d="m-2.842171E-14 0l505.0 0l0 505.0l-505.0 0z" clip-rule="nonzero"/>
```

I think it's the scientific numbers. And I remember you fixing that recently. See https://github.com/mogest/prawn-svg/commit/26cb0a020cae4d1006b44794df28d871c58d74cf

**Comment by mojavelinux** [comment] 2017-02-02 01:51
That's *exactly* what it was. If you change the uppercase E to lowercase e then it works with 0.25.2.

**Comment by mogest** [comment] 2017-02-02 01:57
Nice detective work as per usual, @mojavelinux!

I'll close this off for now.  It was good to give me an incentive to tidy up the error handling code too.

**Closed by mogest** 2017-02-02 01:57 UTC

**Comment by mojavelinux** [comment] 2017-02-02 02:13
:+1:

**Comment by Mogztter** [comment] 2017-02-02 10:21
Wow!
1. Open an issue
2. Go to bed
3. Wake up
4. The issue is gone 😄 

Thank you both 👍
