### ISSUE TITLE
SVG vector image: arrow-head not displayed

### ISSUE THREAD

**Issue by nicesw123** [mogest/prawn-svg#49] opened 2014-12-19 08:55 UTC
Hi!

The following `sample.rb`:
```
require 'rubygems'
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate("arrows.pdf") do |pdf|
  pdf.svg File.read("arrows.svg"), :at => [0, 600], :width => 500
end
```

does **not display the arrow-heads** in the SVG image.

**Source of the SVG `arrows.svg`** (for copy-pasting):
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="200"
   height="200"
   id="svg2"
   version="1.1"
   inkscape:version="0.48.5 r10040"
   sodipodi:docname="New document 1">
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="1.979899"
     inkscape:cx="131.67459"
     inkscape:cy="71.158705"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1680"
     inkscape:window-height="948"
     inkscape:window-x="0"
     inkscape:window-y="31"
     inkscape:window-maximized="1" />
  <defs
     id="defs4">
    <marker
       style="overflow:visible;"
       id="Arrow1Lend"
       refX="0.0"
       refY="0.0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         transform="scale(0.8) rotate(180) translate(12.5,0)"
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1.0pt;"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         id="path3762" />
    </marker>
    <marker
       style="overflow:visible"
       id="Arrow1Lend-3"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 z"
         id="path3762-1"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       style="overflow:visible;"
       id="Arrow1LendK"
       refX="0.0"
       refY="0.0"
       orient="auto"
       inkscape:stockid="Arrow1LendK">
      <path
         transform="scale(0.8) rotate(180) translate(12.5,0)"
         style="stroke:#ff0000;stroke-width:1.0pt;fill:#ff0000;fill-rule:evenodd"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         id="path4230" />
    </marker>
  </defs>
  <metadata
     id="metadata7">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     transform="translate(0,-852.36218)"
     id="layer1"
     inkscape:groupmode="layer"
     inkscape:label="Layer 1">
    <path
       transform="translate(0,852.36218)"
       inkscape:connector-curvature="0"
       id="path2985"
       d="M 26.263966,144.94669 122.22846,94.439059"
       style="fill:none;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;marker-end:url(#Arrow1Lend)" />
    <path
       inkscape:connector-curvature="0"
       id="path2985-7"
       d="M 40.406101,953.8723 136.3706,903.36467"
       style="stroke-linejoin:miter;marker-end:url(#Arrow1LendK);stroke-opacity:1;stroke:#ff0000;stroke-linecap:butt;stroke-width:1px;fill:#ff0000" />
  </g>
</svg>
```

(Issue originally filed at asciidoctor-pdf [ref](https://github.com/asciidoctor/asciidoctor-pdf/issues/75), which uses prawn)

**Comment by mogest** [comment] 2015-01-24 07:36
I'll leave this issue open for a few months; it's the first time anyone has reported its absence, but if I get some downtime I'll give it a bash.  Cheers.

**Comment by mogest** [comment] 2015-05-02 11:28
@nicesw123, I took a look at implementing marker today, but it'd be a huge task to do it and it's not been requested very often.  I don't think I'll get around to doing it, as there are other features missing that are both easier to write and higher up the list.  But if it's something you really want, you might be able to convince someone to write it!

Will close this issue for now.  I appreciate the time you took to report it.

**Comment by abradshaw** [comment] 2015-10-28 12:32
Hi, I am running into this issue (arrow heads missing) from my documentation creation process. My process involves writing in asciidoc, with links to the source SVGs, then converting into a PDF. prawn-svg is involved in this process and I have noticed that the arrow heads are missing from my diagrams

**Comment by mogest** [comment] 2015-10-30 05:54
Hi @abradshaw – prawn-svg doesn't implement a considerable amount of the SVG spec, and I don't really want to have issues open for every feature it doesn't support; there'd be thousands of them!

If you're willing to implement markers, I'd be more than happy to accept a PR.  Or if enough people +1 this issue, I guess it'll be the next thing I chew off, but it's going to be a very complex implementation for something relatively unsubstantial.

**Comment by kastork** [comment] 2016-04-04 17:38
+1

**Comment by mogest** [comment] 2016-04-10 06:01
I'm working on implementing markers now.

**Comment by abradshaw** [comment] 2016-04-10 09:18
Roger thats great news, I currently work arround the issue by manually drawing triangles at the end of my lines :) so it would be great if this was implemented 

:+1:

**Comment by mogest** [comment] 2016-04-10 09:23
Hah, sounds like a pain!

If you would be able to attach a few sample SVG files with some markers—the more complex the better—that'll definitely help me figure out whether I've correctly implemented it or not.

**Comment by abradshaw** [comment] 2016-04-10 09:30
Hi Roger

Seems github doesnt support uploading of SVGs - so I zipped it

[rhev-console-access.svg.zip](https://github.com/mogest/prawn-svg/files/211699/rhev-console-access.svg.zip)

**Comment by AlexanderZobkov** [comment] 2016-04-10 18:13
I also would like to see this feature implemented. 
At the moment, to preserve arrows and other elements that is currently not supported by prawn-svg, we convert SVG files into PNG file by using Batik maven plugin.

**Comment by mogest** [comment] 2016-04-10 21:48
@abradshaw, looks like it's working.  Although the arrows aren't rendered pointing in the direction of the curve, but the SVG renders like this on Chrome and Safari too, so I'm guessing it's rendering as intended?
[rhev-console-access.svg.pdf](https://github.com/mogest/prawn-svg/files/212024/rhev-console-access.svg.pdf)

**Comment by mogest** [comment] 2016-04-11 05:12
I've got an implementation that appears to be working in a branch at https://github.com/mogest/prawn-svg/tree/marker.  If anyone has the time and skill to try it out, I'd appreciate it.  Got a few tests I'd like to write for it before it goes into master.

**Comment by mogest** [comment] 2016-04-24 05:07
Released today as part of 0.24.0.

**Comment by mojavelinux** [comment] 2016-04-24 06:28
:+1: I'll update asciidoctor-pdf to bring the request full circle.

**Comment by mojavelinux** [comment] 2016-04-24 06:40
In the example @abradshaw provided, I think the arrow is supposed to follow the direction of the arc. It renders incorrectly in Chrome, but Firefox, Inkscape, ImageMagick and eog all get it right. That tells me it should appear as follows:

![arrow-on-arc](https://cloud.githubusercontent.com/assets/79351/14765925/0e22a254-09b5-11e6-9436-024f6671a5b2.png)

**Comment by mojavelinux** [comment] 2016-04-24 06:43
Details here: http://stackoverflow.com/a/33384554/208063

**Comment by mogest** [comment] 2016-04-24 08:30
Looking much nicer now!  Thanks for pointing that out.  I'll roll a patch release tomorrow.

[rhev-console-access.svg.pdf](https://github.com/mogest/prawn-svg/files/233342/rhev-console-access.svg.pdf)

**Comment by mojavelinux** [comment] 2016-04-24 08:33
Very slick! You're a hero!

**Comment by abradshaw** [comment] 2016-04-24 10:08
Very cool - thanks so much guys

**Comment by AlexanderZobkov** [comment] 2016-05-02 09:05
It looks like theres are bugs in arrows support.
1) Adobe reader reports that pdf is broken
2) Arrows are not rendered correctly - arrow heads for a first line are not rendered but ok for a second line 
[basic-example.pdf](https://github.com/mogest/prawn-svg/files/244747/basic-example.pdf)
[broken-arrows.svg.txt](https://github.com/mogest/prawn-svg/files/244759/broken-arrows.svg.txt)

Can we reopen the issue or do I need to create a new one?

**Comment by mojavelinux** [comment] 2016-05-02 09:31
I see the missing arrows on the first line. However, I don't see an error when I open the PDF in Adobe Reader. What error are you seeing?

**Comment by mogest** [comment] 2016-05-02 09:36
I've located the problem, thanks for the report.  I don't have Adobe Reader, so please let me know how it's broken.

**Comment by AlexanderZobkov** [comment] 2016-05-02 10:16
Adobe Reader reports that pdf has errors and nothing more =(. 
Instead of Adobe Reader, you can try to use Ghost Script to validate a PDFfile:

```
gs -o nul -sDEVICE=nullpage basic-example.pdf
GPL Ghostscript 8.70 (2009-07-31)
Copyright (C) 2009 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 3.
Page 1
Page 2
Page 3
   **** File did not complete the page properly and may be damaged.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by:
   **** >>>> Doc Writer <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```

**Comment by mogest** [comment] 2016-05-03 21:53
Running that command on the pdf output of the sample SVG you supplied above doesn't generate an error; I think that error is being caused by something upstream from prawn-svg.  If you can provide an SVG that generates a malformed PDF I'm happy to have a look at it; please pop it on a new issue though.

I'll make a patch release for this fix in the next week.

**Comment by AlexanderZobkov** [comment] 2016-05-04 15:19
Hello Roger,

It might be misunderstanding here :smile: 
Do I understand correctly that with changes provided in ee8622d the issue is gone and both arrows are rendered correctly?

**Comment by mogest** [comment] 2016-05-04 21:15
Hi @AlexanderZobkov – yes, the arrows correctly render!  Please see attached PDF.
[a.svg.pdf](https://github.com/mogest/prawn-svg/files/249602/a.svg.pdf)

**Comment by AlexanderZobkov** [comment] 2016-05-05 14:38
I've performed by own experiments, It looks like it's working now. 
Thank you for fixing the issue !

**Comment by AlexanderZobkov** [comment] 2016-05-20 19:38
Hello Roger, 

Is it OK for you to release the patch release? asciidoctor-pdf 1.5.0.alpha.12 will be released soon (probably this weekend) and I would like to upgrade version of prawn-svg to the latest one.

**Comment by mogest** [comment] 2016-05-21 02:07
0.25.1 released, sorry for the delay!

**Closed by mogest** 2016-05-21 02:07 UTC

**Comment by nicesw123** [comment] 2016-05-21 11:24
Hi!

@mogest 
Thanks very much, for implementing this feature!!! Great.

**Comment by abradshaw** [comment] 2016-05-23 17:58
Guys - many thanks for this great work - really appreciated
