### ISSUE TITLE
warning: circular argument reference - font_registry (0.23.0 only)

### ISSUE THREAD

**Issue by aleksejleonov** [mogest/prawn-svg#76] opened 2016-04-01 11:24 UTC
Hi,

After upgrade to **v0.23.0** I got next warning (**v0.22.1** was ok):

`/Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/prawn-svg-0.23.0/lib/prawn/svg/font.rb:23: warning: circular argument reference - font_registry`

Ruby 2.3.0 + Rails 4.2.6.

**Comment by mogest** [comment] 2016-04-02 21:33
Thanks for reporting.  Duplicate of #74.

**Closed by mogest** 2016-04-02 21:33 UTC
