### ISSUE TITLE
test failures in spec/prawn/svg/interface_spec.rb due to rspec 3.12

### ISSUE THREAD

**Issue by Apteryks** [mogest/prawn-svg#151] opened 2023-03-15 17:42 UTC
Hello,

Since updating rspec to 3.12, the following tests fail:
```
Failures:

  1) Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is not set adds content 'B'
     Failure/Error: prawn.send(call, *arguments, **kwarguments)
       #<InstanceDouble(Prawn::Document) (anonymous)> received unexpected message :rectangle with ([0.0, 100.0], 10.0, 10.0)
     # ./lib/prawn/svg/interface.rb:124:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:116:in `block (2 levels) in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:215:in `rewrite_call_arguments'
     # ./lib/prawn/svg/interface.rb:115:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:108:in `block in proc_creator'
     # ./lib/prawn/svg/interface.rb:51:in `block (3 levels) in draw'
     # ./spec/prawn/svg/interface_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./lib/prawn/svg/interface.rb:44:in `block (2 levels) in draw'
     # ./lib/prawn/svg/interface.rb:43:in `block in draw'
     # ./lib/prawn/svg/interface.rb:42:in `draw'
     # ./spec/prawn/svg/interface_spec.rb:49:in `block (6 levels) in <top (required)>'

  2) Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is evenodd adds content 'B*'
     Failure/Error: prawn.send(call, *arguments, **kwarguments)
       #<InstanceDouble(Prawn::Document) (anonymous)> received unexpected message :rectangle with ([0.0, 100.0], 10.0, 10.0)
     # ./lib/prawn/svg/interface.rb:124:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:116:in `block (2 levels) in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:215:in `rewrite_call_arguments'
     # ./lib/prawn/svg/interface.rb:115:in `block in issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:112:in `each'
     # ./lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
     # ./lib/prawn/svg/interface.rb:108:in `block in proc_creator'
     # ./lib/prawn/svg/interface.rb:51:in `block (3 levels) in draw'
     # ./spec/prawn/svg/interface_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./lib/prawn/svg/interface.rb:44:in `block (2 levels) in draw'
     # ./lib/prawn/svg/interface.rb:43:in `block in draw'
     # ./lib/prawn/svg/interface.rb:42:in `draw'
     # ./spec/prawn/svg/interface_spec.rb:60:in `block (6 levels) in <top (required)>'

Finished in 0.71097 seconds (files took 0.21033 seconds to load)
296 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/prawn/svg/interface_spec.rb:45 # Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is not set adds content 'B'
rspec ./spec/prawn/svg/interface_spec.rb:56 # Prawn::SVG::Interface#draw rewrites when fill_and_stroke is issued and fill rule is evenodd adds content 'B*'

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "rspec" arguments: ("-Ilib" "-rprawn-svg") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 1.0 seconds
command "rspec" "-Ilib" "-rprawn-svg" failed with status 1
```
Thanks.

**Comment by mojavelinux** [comment] 2023-11-23 09:50
I'm not able to reproduce this. Steps I took:

* use Ruby 3.0 (the highest version of Ruby tested in CI)
* modify gemspec dependency in prawn-svg.gemspec to `"~> 3.1"`
* clean and reinstall gems
* run `bundle exec rake`

All tests are passing without incident.

**Comment by mogest** [comment] 2024-01-27 22:10
Thanks @Apteryks, I think I saw this problem doing my last round of prawn-svg changes and fixed it.  From memory it was an incompatibility with Ruby 3.2 which is now fixed.

**Closed by mogest** 2024-01-27 22:10 UTC
